// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh-GQvLKtdIU2BOD5BrY9F4IC7IpSURWo',
    appId: '1:287686133723:web:0c2fce37da8f295c1209fe',
    messagingSenderId: '287686133723',
    projectId: 'focusnflow-1ae2f',
    authDomain: 'focusnflow-1ae2f.firebaseapp.com',
    storageBucket: 'focusnflow-1ae2f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOescA5_Gfo7V1WOjhruOp5m8VizHXTQI',
    appId: '1:287686133723:android:1e662ca31edb522c1209fe',
    messagingSenderId: '287686133723',
    projectId: 'focusnflow-1ae2f',
    storageBucket: 'focusnflow-1ae2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCioiFWVse8nxMiQGNblnCH22Kl2nT-PCk',
    appId: '1:287686133723:ios:7033de7eb84764c81209fe',
    messagingSenderId: '287686133723',
    projectId: 'focusnflow-1ae2f',
    storageBucket: 'focusnflow-1ae2f.firebasestorage.app',
    iosBundleId: 'com.example.focusnflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCioiFWVse8nxMiQGNblnCH22Kl2nT-PCk',
    appId: '1:287686133723:ios:7033de7eb84764c81209fe',
    messagingSenderId: '287686133723',
    projectId: 'focusnflow-1ae2f',
    storageBucket: 'focusnflow-1ae2f.firebasestorage.app',
    iosBundleId: 'com.example.focusnflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh-GQvLKtdIU2BOD5BrY9F4IC7IpSURWo',
    appId: '1:287686133723:web:31d677e5a6b844631209fe',
    messagingSenderId: '287686133723',
    projectId: 'focusnflow-1ae2f',
    authDomain: 'focusnflow-1ae2f.firebaseapp.com',
    storageBucket: 'focusnflow-1ae2f.firebasestorage.app',
  );
}
